# Generated by Django 2.2.6 on 2019-10-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
    ]
