# Generated by Django 2.2.6 on 2019-12-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': True, 'verbose_name': 'Abogado'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False, 'verbose_name': 'Genero'},
        ),
    ]
