# Generated by Django 2.2.6 on 2019-12-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbAbogados',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=51)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('tarjeta_p', models.IntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=154, null=True)),
                ('ciudadnombre', models.CharField(blank=True, db_column='ciudadNombre', max_length=27, null=True)),
                ('departamento', models.CharField(blank=True, max_length=18, null=True)),
                ('direccion2', models.CharField(blank=True, max_length=154, null=True)),
                ('empresa', models.CharField(blank=True, max_length=56, null=True)),
                ('celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('celular1', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo2', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo1', models.CharField(blank=True, max_length=15, null=True)),
                ('fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('e_mail1', models.CharField(blank=True, max_length=67, null=True)),
                ('e_mail2', models.CharField(blank=True, max_length=67, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('fechaexpedicion', models.DateField(blank=True, db_column='fechaExpedicion', null=True)),
                ('actualizacion', models.ForeignKey(blank=True, db_column='actualizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.AsesoresDb')),
                ('ciudad', models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DbAbogados.ciudad+', to='registro_abogados.Municipio')),
                ('ciudad2', models.ForeignKey(blank=True, db_column='ciudad2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DbAbogados.ciudad2+', to='registro_abogados.Municipio')),
                ('ciudadexpedicion', models.ForeignKey(blank=True, db_column='ciudadExpedicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DbAbogados.ciudadexpedicion+', to='registro_abogados.Municipio')),
                ('contacto', models.ForeignKey(blank=True, db_column='contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.OrigenContacto')),
                ('genero', models.ForeignKey(db_column='genero', on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.Genero')),
                ('perfil', models.ForeignKey(blank=True, db_column='perfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.Perfil')),
            ],
            options={
                'verbose_name': 'Abogado',
                'db_table': 'db_abogados',
                'managed': True,
            },
        ),
    ]
