# Generated by Django 2.2.6 on 2019-10-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0002_auto_20191018_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salariomin',
            options={},
        ),
    ]
