# Generated by Django 2.2.6 on 2019-10-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0003_auto_20191018_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salariomin',
            options={'managed': False},
        ),
    ]
