# Generated by Django 2.2.6 on 2019-11-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0004_auto_20191024_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': True},
        ),
    ]
