# Generated by Django 2.2.6 on 2019-11-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0005_auto_20191107_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbabogados',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro_abogados.Genero'),
        ),
    ]
