# Generated by Django 2.2.6 on 2019-11-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0006_auto_20191107_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': True},
        ),
    ]
