# Generated by Django 2.2.6 on 2019-11-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0007_auto_20191107_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False},
        ),
    ]
