# Generated by Django 2.2.6 on 2019-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0008_auto_20191107_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('prueba', models.CharField(max_length=150)),
            ],
        ),
    ]
