# Generated by Django 2.2.6 on 2019-11-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0009_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbabogados',
            options={'managed': True},
        ),
    ]
