# Generated by Django 2.2.6 on 2019-11-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_abogados', '0010_auto_20191115_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbabogados',
            name='ciudad',
            field=models.ForeignKey(blank=True, db_column='ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad', to='registro_abogados.Municipio'),
        ),
        migrations.AlterField(
            model_name='dbabogados',
            name='ciudad2',
            field=models.ForeignKey(blank=True, db_column='ciudad2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad2', to='registro_abogados.Municipio'),
        ),
        migrations.AlterField(
            model_name='dbabogados',
            name='ciudadexpedicion',
            field=models.ForeignKey(blank=True, db_column='ciudadExpedicion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudadexpedicion', to='registro_abogados.Municipio'),
        ),
        migrations.AlterField(
            model_name='dbabogados',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.Genero'),
        ),
        migrations.AlterField(
            model_name='dbabogados',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='perfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro_abogados.Perfil'),
        ),
    ]
