# Generated by Django 2.2.6 on 2019-11-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimiento',
            options={'managed': True},
        ),
    ]
